# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a502cdd02822997f9f13010f505f03065579b55650c567b288a0a2b0895c5f33a785621950e777ccc00179e1f885e0a3b0e562533d2c22f045e29e95e30d90da
  aws_access_key_id: your_aws_access_key_id
  aws_secret_access_key: your_aws_secret_access_key
  s3_bucket: your_bucket_name
  s3_region: 'us-east-1' # với case của mình chỉ chạy với region us-east-1, chưa rõ nguyên nhân vì sao

test:
  secret_key_base: 0d5c16ff950ffd441969f684a2fdc0ab98ce605d41605832a3163a0d56557214836d8f8a6c640465dad4565c610c8baa84bc891f00e799f6ea7332595a994975

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
